window.onload = function() {

  document.getElementById('FD1').innerHTML = data["Table4_1"]["Freeze Dryer 1"][1]
  document.getElementById('FD1_tray1').innerHTML = data["Table4_1"]["Freeze Dryer 1"][2]
  document.getElementById('FD1_tray2').innerHTML = data["Table4_1"]["Freeze Dryer 1"][3]
  document.getElementById('FD1_tray3').innerHTML = data["Table4_1"]["Freeze Dryer 1"][4]
  document.getElementById('FD1_tray4').innerHTML = data["Table4_1"]["Freeze Dryer 1"][5]
  document.getElementById('FD1_tray5').innerHTML = data["Table4_1"]["Freeze Dryer 1"][6]
  document.getElementById('FD1_tray6').innerHTML = data["Table4_1"]["Freeze Dryer 1"][7]
  document.getElementById('FD1_tray7').innerHTML = data["Table4_1"]["Freeze Dryer 1"][8]
  document.getElementById('FD1_tray8').innerHTML = data["Table4_1"]["Freeze Dryer 1"][9]
  document.getElementById('FD1_tray9').innerHTML = data["Table4_1"]["Freeze Dryer 1"][10]
  document.getElementById('FD1_tray10').innerHTML = data["Table4_1"]["Freeze Dryer 1"][11]
  document.getElementById('FD1_tray11').innerHTML = data["Table4_1"]["Freeze Dryer 1"][12]
  document.getElementById('FD1_tray12').innerHTML = data["Table4_1"]["Freeze Dryer 1"][13]
  document.getElementById('FD1_tray13').innerHTML = data["Table4_1"]["Freeze Dryer 1"][14]
  document.getElementById('FD1_tray14').innerHTML = data["Table4_1"]["Freeze Dryer 1"][15]
  document.getElementById('FD1_tray15').innerHTML = data["Table4_1"]["Freeze Dryer 1"][16]

  document.getElementById('FD2').innerHTML = data["Table4_2"]["Freeze Dryer 2"][1]
  document.getElementById('FD2_tray1').innerHTML = data["Table4_2"]["Freeze Dryer 2"][2]
  document.getElementById('FD2_tray2').innerHTML = data["Table4_2"]["Freeze Dryer 2"][3]
  document.getElementById('FD2_tray3').innerHTML = data["Table4_2"]["Freeze Dryer 2"][4]
  document.getElementById('FD2_tray4').innerHTML = data["Table4_2"]["Freeze Dryer 2"][5]
  document.getElementById('FD2_tray5').innerHTML = data["Table4_2"]["Freeze Dryer 2"][6]
  document.getElementById('FD2_tray6').innerHTML = data["Table4_2"]["Freeze Dryer 2"][7]
  document.getElementById('FD2_tray7').innerHTML = data["Table4_2"]["Freeze Dryer 2"][8]
  document.getElementById('FD2_tray8').innerHTML = data["Table4_2"]["Freeze Dryer 2"][9]
  document.getElementById('FD2_tray9').innerHTML = data["Table4_2"]["Freeze Dryer 2"][10]
  document.getElementById('FD2_tray10').innerHTML = data["Table4_2"]["Freeze Dryer 2"][11]
  document.getElementById('FD2_tray11').innerHTML = data["Table4_2"]["Freeze Dryer 2"][12]
  document.getElementById('FD2_tray12').innerHTML = data["Table4_2"]["Freeze Dryer 2"][13]
  document.getElementById('FD2_tray13').innerHTML = data["Table4_2"]["Freeze Dryer 2"][14]
  document.getElementById('FD2_tray14').innerHTML = data["Table4_2"]["Freeze Dryer 2"][15]
  document.getElementById('FD2_tray15').innerHTML = data["Table4_2"]["Freeze Dryer 2"][16]

  document.getElementById('FD3').innerHTML = data["Table4_3"]["Freeze Dryer 3"][1]
  document.getElementById('FD3_tray1').innerHTML = data["Table4_3"]["Freeze Dryer 3"][2]
  document.getElementById('FD3_tray2').innerHTML = data["Table4_3"]["Freeze Dryer 3"][3]
  document.getElementById('FD3_tray3').innerHTML = data["Table4_3"]["Freeze Dryer 3"][4]
  document.getElementById('FD3_tray4').innerHTML = data["Table4_3"]["Freeze Dryer 3"][5]
  document.getElementById('FD3_tray5').innerHTML = data["Table4_3"]["Freeze Dryer 3"][6]
  document.getElementById('FD3_tray6').innerHTML = data["Table4_3"]["Freeze Dryer 3"][7]
  document.getElementById('FD3_tray7').innerHTML = data["Table4_3"]["Freeze Dryer 3"][8]
  document.getElementById('FD3_tray8').innerHTML = data["Table4_3"]["Freeze Dryer 3"][9]
  document.getElementById('FD3_tray9').innerHTML = data["Table4_3"]["Freeze Dryer 3"][10]
  document.getElementById('FD3_tray10').innerHTML = data["Table4_3"]["Freeze Dryer 3"][11]
  document.getElementById('FD3_tray11').innerHTML = data["Table4_3"]["Freeze Dryer 3"][12]
  document.getElementById('FD3_tray12').innerHTML = data["Table4_3"]["Freeze Dryer 3"][13]
  document.getElementById('FD3_tray13').innerHTML = data["Table4_3"]["Freeze Dryer 3"][14]
  document.getElementById('FD3_tray14').innerHTML = data["Table4_3"]["Freeze Dryer 3"][15]
  document.getElementById('FD3_tray15').innerHTML = data["Table4_3"]["Freeze Dryer 3"][16]

  document.getElementById('FD4').innerHTML = data["Table4_4"]["Freeze Dryer 4"][1]
  document.getElementById('FD4_tray1').innerHTML = data["Table4_4"]["Freeze Dryer 4"][2]
  document.getElementById('FD4_tray2').innerHTML = data["Table4_4"]["Freeze Dryer 4"][3]
  document.getElementById('FD4_tray3').innerHTML = data["Table4_4"]["Freeze Dryer 4"][4]
  document.getElementById('FD4_tray4').innerHTML = data["Table4_4"]["Freeze Dryer 4"][5]
  document.getElementById('FD4_tray5').innerHTML = data["Table4_4"]["Freeze Dryer 4"][6]
  document.getElementById('FD4_tray6').innerHTML = data["Table4_4"]["Freeze Dryer 4"][7]
  document.getElementById('FD4_tray7').innerHTML = data["Table4_4"]["Freeze Dryer 4"][8]
  document.getElementById('FD4_tray8').innerHTML = data["Table4_4"]["Freeze Dryer 4"][9]
  document.getElementById('FD4_tray9').innerHTML = data["Table4_4"]["Freeze Dryer 4"][10]
  document.getElementById('FD4_tray10').innerHTML = data["Table4_4"]["Freeze Dryer 4"][11]
  document.getElementById('FD4_tray11').innerHTML = data["Table4_4"]["Freeze Dryer 4"][12]
  document.getElementById('FD4_tray12').innerHTML = data["Table4_4"]["Freeze Dryer 4"][13]
  document.getElementById('FD4_tray13').innerHTML = data["Table4_4"]["Freeze Dryer 4"][14]
  document.getElementById('FD4_tray14').innerHTML = data["Table4_4"]["Freeze Dryer 4"][15]
  document.getElementById('FD4_tray15').innerHTML = data["Table4_4"]["Freeze Dryer 4"][16]

  document.getElementById('FD5').innerHTML = data["Table4_5"]["Freeze Dryer 5"][1]
  document.getElementById('FD5_tray1').innerHTML = data["Table4_5"]["Freeze Dryer 5"][2]
  document.getElementById('FD5_tray2').innerHTML = data["Table4_5"]["Freeze Dryer 5"][3]
  document.getElementById('FD5_tray3').innerHTML = data["Table4_5"]["Freeze Dryer 5"][4]
  document.getElementById('FD5_tray4').innerHTML = data["Table4_5"]["Freeze Dryer 5"][5]
  document.getElementById('FD5_tray5').innerHTML = data["Table4_5"]["Freeze Dryer 5"][6]
  document.getElementById('FD5_tray6').innerHTML = data["Table4_5"]["Freeze Dryer 5"][7]
  document.getElementById('FD5_tray7').innerHTML = data["Table4_5"]["Freeze Dryer 5"][8]
  document.getElementById('FD5_tray8').innerHTML = data["Table4_5"]["Freeze Dryer 5"][9]
  document.getElementById('FD5_tray9').innerHTML = data["Table4_5"]["Freeze Dryer 5"][10]
  document.getElementById('FD5_tray10').innerHTML = data["Table4_5"]["Freeze Dryer 5"][11]
  document.getElementById('FD5_tray11').innerHTML = data["Table4_5"]["Freeze Dryer 5"][12]
  document.getElementById('FD5_tray12').innerHTML = data["Table4_5"]["Freeze Dryer 5"][13]
  document.getElementById('FD5_tray13').innerHTML = data["Table4_5"]["Freeze Dryer 5"][14]
  document.getElementById('FD5_tray14').innerHTML = data["Table4_5"]["Freeze Dryer 5"][15]
  document.getElementById('FD5_tray15').innerHTML = data["Table4_5"]["Freeze Dryer 5"][16]

  document.getElementById('FD6').innerHTML = data["Table4_6"]["Freeze Dryer 6"][1]
  document.getElementById('FD6_tray1').innerHTML = data["Table4_6"]["Freeze Dryer 6"][2]
  document.getElementById('FD6_tray2').innerHTML = data["Table4_6"]["Freeze Dryer 6"][3]
  document.getElementById('FD6_tray3').innerHTML = data["Table4_6"]["Freeze Dryer 6"][4]
  document.getElementById('FD6_tray4').innerHTML = data["Table4_6"]["Freeze Dryer 6"][5]
  document.getElementById('FD6_tray5').innerHTML = data["Table4_6"]["Freeze Dryer 6"][6]
  document.getElementById('FD6_tray6').innerHTML = data["Table4_6"]["Freeze Dryer 6"][7]
  document.getElementById('FD6_tray7').innerHTML = data["Table4_6"]["Freeze Dryer 6"][8]
  document.getElementById('FD6_tray8').innerHTML = data["Table4_6"]["Freeze Dryer 6"][9]
  document.getElementById('FD6_tray9').innerHTML = data["Table4_6"]["Freeze Dryer 6"][10]
  document.getElementById('FD6_tray10').innerHTML = data["Table4_6"]["Freeze Dryer 6"][11]
  document.getElementById('FD6_tray11').innerHTML = data["Table4_6"]["Freeze Dryer 6"][12]
  document.getElementById('FD6_tray12').innerHTML = data["Table4_6"]["Freeze Dryer 6"][13]
  document.getElementById('FD6_tray13').innerHTML = data["Table4_6"]["Freeze Dryer 6"][14]
  document.getElementById('FD6_tray14').innerHTML = data["Table4_6"]["Freeze Dryer 6"][15]
  document.getElementById('FD6_tray15').innerHTML = data["Table4_6"]["Freeze Dryer 6"][16]

  document.getElementById('FD7').innerHTML = data["Table4_7"]["Freeze Dryer 7"][1]
  document.getElementById('FD7_tray1').innerHTML = data["Table4_7"]["Freeze Dryer 7"][2]
  document.getElementById('FD7_tray2').innerHTML = data["Table4_7"]["Freeze Dryer 7"][3]
  document.getElementById('FD7_tray3').innerHTML = data["Table4_7"]["Freeze Dryer 7"][4]
  document.getElementById('FD7_tray4').innerHTML = data["Table4_7"]["Freeze Dryer 7"][5]
  document.getElementById('FD7_tray5').innerHTML = data["Table4_7"]["Freeze Dryer 7"][6]
  document.getElementById('FD7_tray6').innerHTML = data["Table4_7"]["Freeze Dryer 7"][7]
  document.getElementById('FD7_tray7').innerHTML = data["Table4_7"]["Freeze Dryer 7"][8]
  document.getElementById('FD7_tray8').innerHTML = data["Table4_7"]["Freeze Dryer 7"][9]
  document.getElementById('FD7_tray9').innerHTML = data["Table4_7"]["Freeze Dryer 7"][10]
  document.getElementById('FD7_tray10').innerHTML = data["Table4_7"]["Freeze Dryer 7"][11]
  document.getElementById('FD7_tray11').innerHTML = data["Table4_7"]["Freeze Dryer 7"][12]
  document.getElementById('FD7_tray12').innerHTML = data["Table4_7"]["Freeze Dryer 7"][13]
  document.getElementById('FD7_tray13').innerHTML = data["Table4_7"]["Freeze Dryer 7"][14]
  document.getElementById('FD7_tray14').innerHTML = data["Table4_7"]["Freeze Dryer 7"][15]
  document.getElementById('FD7_tray15').innerHTML = data["Table4_7"]["Freeze Dryer 7"][16]

  document.getElementById('FD8').innerHTML = data["Table4_8"]["Freeze Dryer 8"][1]
  document.getElementById('FD8_tray1').innerHTML = data["Table4_8"]["Freeze Dryer 8"][2]
  document.getElementById('FD8_tray2').innerHTML = data["Table4_8"]["Freeze Dryer 8"][3]
  document.getElementById('FD8_tray3').innerHTML = data["Table4_8"]["Freeze Dryer 8"][4]
  document.getElementById('FD8_tray4').innerHTML = data["Table4_8"]["Freeze Dryer 8"][5]
  document.getElementById('FD8_tray5').innerHTML = data["Table4_8"]["Freeze Dryer 8"][6]
  document.getElementById('FD8_tray6').innerHTML = data["Table4_8"]["Freeze Dryer 8"][7]
  document.getElementById('FD8_tray7').innerHTML = data["Table4_8"]["Freeze Dryer 8"][8]
  document.getElementById('FD8_tray8').innerHTML = data["Table4_8"]["Freeze Dryer 8"][9]
  document.getElementById('FD8_tray9').innerHTML = data["Table4_8"]["Freeze Dryer 8"][10]
  document.getElementById('FD8_tray10').innerHTML = data["Table4_8"]["Freeze Dryer 8"][11]
  document.getElementById('FD8_tray11').innerHTML = data["Table4_8"]["Freeze Dryer 8"][12]
  document.getElementById('FD8_tray12').innerHTML = data["Table4_8"]["Freeze Dryer 8"][13]
  document.getElementById('FD8_tray13').innerHTML = data["Table4_8"]["Freeze Dryer 8"][14]
  document.getElementById('FD8_tray14').innerHTML = data["Table4_8"]["Freeze Dryer 8"][15]
  document.getElementById('FD8_tray15').innerHTML = data["Table4_8"]["Freeze Dryer 8"][16]

  document.getElementById('FD9').innerHTML = data["Table4_9"]["Freeze Dryer 9"][1]
  document.getElementById('FD9_tray1').innerHTML = data["Table4_9"]["Freeze Dryer 9"][2]
  document.getElementById('FD9_tray2').innerHTML = data["Table4_9"]["Freeze Dryer 9"][3]
  document.getElementById('FD9_tray3').innerHTML = data["Table4_9"]["Freeze Dryer 9"][4]
  document.getElementById('FD9_tray4').innerHTML = data["Table4_9"]["Freeze Dryer 9"][5]
  document.getElementById('FD9_tray5').innerHTML = data["Table4_9"]["Freeze Dryer 9"][6]
  document.getElementById('FD9_tray6').innerHTML = data["Table4_9"]["Freeze Dryer 9"][7]
  document.getElementById('FD9_tray7').innerHTML = data["Table4_9"]["Freeze Dryer 9"][8]
  document.getElementById('FD9_tray8').innerHTML = data["Table4_9"]["Freeze Dryer 9"][9]
  document.getElementById('FD9_tray9').innerHTML = data["Table4_9"]["Freeze Dryer 9"][10]
  document.getElementById('FD9_tray10').innerHTML = data["Table4_9"]["Freeze Dryer 9"][11]
  document.getElementById('FD9_tray11').innerHTML = data["Table4_9"]["Freeze Dryer 9"][12]
  document.getElementById('FD9_tray12').innerHTML = data["Table4_9"]["Freeze Dryer 9"][13]
  document.getElementById('FD9_tray13').innerHTML = data["Table4_9"]["Freeze Dryer 9"][14]
  document.getElementById('FD9_tray14').innerHTML = data["Table4_9"]["Freeze Dryer 9"][15]
  document.getElementById('FD9_tray15').innerHTML = data["Table4_9"]["Freeze Dryer 9"][16]

  document.getElementById('FD10').innerHTML = data["Table4_10"]["Freeze Dryer 10"][1]
  document.getElementById('FD10_tray1').innerHTML = data["Table4_10"]["Freeze Dryer 10"][2]
  document.getElementById('FD10_tray2').innerHTML = data["Table4_10"]["Freeze Dryer 10"][3]
  document.getElementById('FD10_tray3').innerHTML = data["Table4_10"]["Freeze Dryer 10"][4]
  document.getElementById('FD10_tray4').innerHTML = data["Table4_10"]["Freeze Dryer 10"][5]
  document.getElementById('FD10_tray5').innerHTML = data["Table4_10"]["Freeze Dryer 10"][6]
  document.getElementById('FD10_tray6').innerHTML = data["Table4_10"]["Freeze Dryer 10"][7]
  document.getElementById('FD10_tray7').innerHTML = data["Table4_10"]["Freeze Dryer 10"][8]
  document.getElementById('FD10_tray8').innerHTML = data["Table4_10"]["Freeze Dryer 10"][9]
  document.getElementById('FD10_tray9').innerHTML = data["Table4_10"]["Freeze Dryer 10"][10]
  document.getElementById('FD10_tray10').innerHTML = data["Table4_10"]["Freeze Dryer 10"][11]
  document.getElementById('FD10_tray11').innerHTML = data["Table4_10"]["Freeze Dryer 10"][12]
  document.getElementById('FD10_tray12').innerHTML = data["Table4_10"]["Freeze Dryer 10"][13]
  document.getElementById('FD10_tray13').innerHTML = data["Table4_10"]["Freeze Dryer 10"][14]
  document.getElementById('FD10_tray14').innerHTML = data["Table4_10"]["Freeze Dryer 10"][15]
  document.getElementById('FD10_tray15').innerHTML = data["Table4_10"]["Freeze Dryer 10"][16]

  document.getElementById('FD11').innerHTML = data["Table4_11"]["Freeze Dryer 11"][1]
  document.getElementById('FD11_tray1').innerHTML = data["Table4_11"]["Freeze Dryer 11"][2]
  document.getElementById('FD11_tray2').innerHTML = data["Table4_11"]["Freeze Dryer 11"][3]
  document.getElementById('FD11_tray3').innerHTML = data["Table4_11"]["Freeze Dryer 11"][4]
  document.getElementById('FD11_tray4').innerHTML = data["Table4_11"]["Freeze Dryer 11"][5]
  document.getElementById('FD11_tray5').innerHTML = data["Table4_11"]["Freeze Dryer 11"][6]
  document.getElementById('FD11_tray6').innerHTML = data["Table4_11"]["Freeze Dryer 11"][7]
  document.getElementById('FD11_tray7').innerHTML = data["Table4_11"]["Freeze Dryer 11"][8]
  document.getElementById('FD11_tray8').innerHTML = data["Table4_11"]["Freeze Dryer 11"][9]
  document.getElementById('FD11_tray9').innerHTML = data["Table4_11"]["Freeze Dryer 11"][10]
  document.getElementById('FD11_tray10').innerHTML = data["Table4_11"]["Freeze Dryer 11"][11]
  document.getElementById('FD11_tray11').innerHTML = data["Table4_11"]["Freeze Dryer 11"][12]
  document.getElementById('FD11_tray12').innerHTML = data["Table4_11"]["Freeze Dryer 11"][13]
  document.getElementById('FD11_tray13').innerHTML = data["Table4_11"]["Freeze Dryer 11"][14]
  document.getElementById('FD11_tray14').innerHTML = data["Table4_11"]["Freeze Dryer 11"][15]
  document.getElementById('FD11_tray15').innerHTML = data["Table4_11"]["Freeze Dryer 11"][16]

  document.getElementById('FD12').innerHTML = data["Table4_12"]["Freeze Dryer 12"][1]
  document.getElementById('FD12_tray1').innerHTML = data["Table4_12"]["Freeze Dryer 12"][2]
  document.getElementById('FD12_tray2').innerHTML = data["Table4_12"]["Freeze Dryer 12"][3]
  document.getElementById('FD12_tray3').innerHTML = data["Table4_12"]["Freeze Dryer 12"][4]
  document.getElementById('FD12_tray4').innerHTML = data["Table4_12"]["Freeze Dryer 12"][5]
  document.getElementById('FD12_tray5').innerHTML = data["Table4_12"]["Freeze Dryer 12"][6]
  document.getElementById('FD12_tray6').innerHTML = data["Table4_12"]["Freeze Dryer 12"][7]
  document.getElementById('FD12_tray7').innerHTML = data["Table4_12"]["Freeze Dryer 12"][8]
  document.getElementById('FD12_tray8').innerHTML = data["Table4_12"]["Freeze Dryer 12"][9]
  document.getElementById('FD12_tray9').innerHTML = data["Table4_12"]["Freeze Dryer 12"][10]
  document.getElementById('FD12_tray10').innerHTML = data["Table4_12"]["Freeze Dryer 12"][11]
  document.getElementById('FD12_tray11').innerHTML = data["Table4_12"]["Freeze Dryer 12"][12]
  document.getElementById('FD12_tray12').innerHTML = data["Table4_12"]["Freeze Dryer 12"][13]
  document.getElementById('FD12_tray13').innerHTML = data["Table4_12"]["Freeze Dryer 12"][14]
  document.getElementById('FD12_tray14').innerHTML = data["Table4_12"]["Freeze Dryer 12"][15]
  document.getElementById('FD12_tray15').innerHTML = data["Table4_12"]["Freeze Dryer 12"][16]

  document.getElementById('FD13').innerHTML = data["Table4_13"]["Freeze Dryer 13"][1]
  document.getElementById('FD13_tray1').innerHTML = data["Table4_13"]["Freeze Dryer 13"][2]
  document.getElementById('FD13_tray2').innerHTML = data["Table4_13"]["Freeze Dryer 13"][3]
  document.getElementById('FD13_tray3').innerHTML = data["Table4_13"]["Freeze Dryer 13"][4]
  document.getElementById('FD13_tray4').innerHTML = data["Table4_13"]["Freeze Dryer 13"][5]
  document.getElementById('FD13_tray5').innerHTML = data["Table4_13"]["Freeze Dryer 13"][6]
  document.getElementById('FD13_tray6').innerHTML = data["Table4_13"]["Freeze Dryer 13"][7]
  document.getElementById('FD13_tray7').innerHTML = data["Table4_13"]["Freeze Dryer 13"][8]
  document.getElementById('FD13_tray8').innerHTML = data["Table4_13"]["Freeze Dryer 13"][9]
  document.getElementById('FD13_tray9').innerHTML = data["Table4_13"]["Freeze Dryer 13"][10]
  document.getElementById('FD13_tray10').innerHTML = data["Table4_13"]["Freeze Dryer 13"][11]
  document.getElementById('FD13_tray11').innerHTML = data["Table4_13"]["Freeze Dryer 13"][12]
  document.getElementById('FD13_tray12').innerHTML = data["Table4_13"]["Freeze Dryer 13"][13]
  document.getElementById('FD13_tray13').innerHTML = data["Table4_13"]["Freeze Dryer 13"][14]
  document.getElementById('FD13_tray14').innerHTML = data["Table4_13"]["Freeze Dryer 13"][15]
  document.getElementById('FD13_tray15').innerHTML = data["Table4_13"]["Freeze Dryer 13"][16]

  document.getElementById('FD14').innerHTML = data["Table4_14"]["Freeze Dryer 14"][1]
  document.getElementById('FD14_tray1').innerHTML = data["Table4_14"]["Freeze Dryer 14"][2]
  document.getElementById('FD14_tray2').innerHTML = data["Table4_14"]["Freeze Dryer 14"][3]
  document.getElementById('FD14_tray3').innerHTML = data["Table4_14"]["Freeze Dryer 14"][4]
  document.getElementById('FD14_tray4').innerHTML = data["Table4_14"]["Freeze Dryer 14"][5]
  document.getElementById('FD14_tray5').innerHTML = data["Table4_14"]["Freeze Dryer 14"][6]
  document.getElementById('FD14_tray6').innerHTML = data["Table4_14"]["Freeze Dryer 14"][7]
  document.getElementById('FD14_tray7').innerHTML = data["Table4_14"]["Freeze Dryer 14"][8]
  document.getElementById('FD14_tray8').innerHTML = data["Table4_14"]["Freeze Dryer 14"][9]
  document.getElementById('FD14_tray9').innerHTML = data["Table4_14"]["Freeze Dryer 14"][10]
  document.getElementById('FD14_tray10').innerHTML = data["Table4_14"]["Freeze Dryer 14"][11]
  document.getElementById('FD14_tray11').innerHTML = data["Table4_14"]["Freeze Dryer 14"][12]
  document.getElementById('FD14_tray12').innerHTML = data["Table4_14"]["Freeze Dryer 14"][13]
  document.getElementById('FD14_tray13').innerHTML = data["Table4_14"]["Freeze Dryer 14"][14]
  document.getElementById('FD14_tray14').innerHTML = data["Table4_14"]["Freeze Dryer 14"][15]
  document.getElementById('FD14_tray15').innerHTML = data["Table4_14"]["Freeze Dryer 14"][16]

  document.getElementById('FD15').innerHTML = data["Table4_15"]["Freeze Dryer 15"][1]
  document.getElementById('FD15_tray1').innerHTML = data["Table4_15"]["Freeze Dryer 15"][2]
  document.getElementById('FD15_tray2').innerHTML = data["Table4_15"]["Freeze Dryer 15"][3]
  document.getElementById('FD15_tray3').innerHTML = data["Table4_15"]["Freeze Dryer 15"][4]
  document.getElementById('FD15_tray4').innerHTML = data["Table4_15"]["Freeze Dryer 15"][5]
  document.getElementById('FD15_tray5').innerHTML = data["Table4_15"]["Freeze Dryer 15"][6]
  document.getElementById('FD15_tray6').innerHTML = data["Table4_15"]["Freeze Dryer 15"][7]
  document.getElementById('FD15_tray7').innerHTML = data["Table4_15"]["Freeze Dryer 15"][8]
  document.getElementById('FD15_tray8').innerHTML = data["Table4_15"]["Freeze Dryer 15"][9]
  document.getElementById('FD15_tray9').innerHTML = data["Table4_15"]["Freeze Dryer 15"][10]
  document.getElementById('FD15_tray10').innerHTML = data["Table4_15"]["Freeze Dryer 15"][11]
  document.getElementById('FD15_tray11').innerHTML = data["Table4_15"]["Freeze Dryer 15"][12]
  document.getElementById('FD15_tray12').innerHTML = data["Table4_15"]["Freeze Dryer 15"][13]
  document.getElementById('FD15_tray13').innerHTML = data["Table4_15"]["Freeze Dryer 15"][14]
  document.getElementById('FD15_tray14').innerHTML = data["Table4_15"]["Freeze Dryer 15"][15]
  document.getElementById('FD15_tray15').innerHTML = data["Table4_15"]["Freeze Dryer 15"][16]

  document.getElementById('FD16').innerHTML = data["Table4_16"]["Freeze Dryer 16"][1]
  document.getElementById('FD16_tray1').innerHTML = data["Table4_16"]["Freeze Dryer 16"][2]
  document.getElementById('FD16_tray2').innerHTML = data["Table4_16"]["Freeze Dryer 16"][3]
  document.getElementById('FD16_tray3').innerHTML = data["Table4_16"]["Freeze Dryer 16"][4]
  document.getElementById('FD16_tray4').innerHTML = data["Table4_16"]["Freeze Dryer 16"][5]
  document.getElementById('FD16_tray5').innerHTML = data["Table4_16"]["Freeze Dryer 16"][6]
  document.getElementById('FD16_tray6').innerHTML = data["Table4_16"]["Freeze Dryer 16"][7]
  document.getElementById('FD16_tray7').innerHTML = data["Table4_16"]["Freeze Dryer 16"][8]
  document.getElementById('FD16_tray8').innerHTML = data["Table4_16"]["Freeze Dryer 16"][9]
  document.getElementById('FD16_tray9').innerHTML = data["Table4_16"]["Freeze Dryer 16"][10]
  document.getElementById('FD16_tray10').innerHTML = data["Table4_16"]["Freeze Dryer 16"][11]
  document.getElementById('FD16_tray11').innerHTML = data["Table4_16"]["Freeze Dryer 16"][12]
  document.getElementById('FD16_tray12').innerHTML = data["Table4_16"]["Freeze Dryer 16"][13]
  document.getElementById('FD16_tray13').innerHTML = data["Table4_16"]["Freeze Dryer 16"][14]
  document.getElementById('FD16_tray14').innerHTML = data["Table4_16"]["Freeze Dryer 16"][15]
  document.getElementById('FD16_tray15').innerHTML = data["Table4_16"]["Freeze Dryer 16"][16]

  document.getElementById('FD17').innerHTML = data["Table4_17"]["Freeze Dryer 17"][1]
  document.getElementById('FD17_tray1').innerHTML = data["Table4_17"]["Freeze Dryer 17"][2]
  document.getElementById('FD17_tray2').innerHTML = data["Table4_17"]["Freeze Dryer 17"][3]
  document.getElementById('FD17_tray3').innerHTML = data["Table4_17"]["Freeze Dryer 17"][4]
  document.getElementById('FD17_tray4').innerHTML = data["Table4_17"]["Freeze Dryer 17"][5]
  document.getElementById('FD17_tray5').innerHTML = data["Table4_17"]["Freeze Dryer 17"][6]
  document.getElementById('FD17_tray6').innerHTML = data["Table4_17"]["Freeze Dryer 17"][7]
  document.getElementById('FD17_tray7').innerHTML = data["Table4_17"]["Freeze Dryer 17"][8]
  document.getElementById('FD17_tray8').innerHTML = data["Table4_17"]["Freeze Dryer 17"][9]
  document.getElementById('FD17_tray9').innerHTML = data["Table4_17"]["Freeze Dryer 17"][10]
  document.getElementById('FD17_tray10').innerHTML = data["Table4_17"]["Freeze Dryer 17"][11]
  document.getElementById('FD17_tray11').innerHTML = data["Table4_17"]["Freeze Dryer 17"][12]
  document.getElementById('FD17_tray12').innerHTML = data["Table4_17"]["Freeze Dryer 17"][13]
  document.getElementById('FD17_tray13').innerHTML = data["Table4_17"]["Freeze Dryer 17"][14]
  document.getElementById('FD17_tray14').innerHTML = data["Table4_17"]["Freeze Dryer 17"][15]
  document.getElementById('FD17_tray15').innerHTML = data["Table4_17"]["Freeze Dryer 17"][16]

  document.getElementById('FD18').innerHTML = data["Table4_18"]["Freeze Dryer 18"][1]
  document.getElementById('FD18_tray1').innerHTML = data["Table4_18"]["Freeze Dryer 18"][2]
  document.getElementById('FD18_tray2').innerHTML = data["Table4_18"]["Freeze Dryer 18"][3]
  document.getElementById('FD18_tray3').innerHTML = data["Table4_18"]["Freeze Dryer 18"][4]
  document.getElementById('FD18_tray4').innerHTML = data["Table4_18"]["Freeze Dryer 18"][5]
  document.getElementById('FD18_tray5').innerHTML = data["Table4_18"]["Freeze Dryer 18"][6]
  document.getElementById('FD18_tray6').innerHTML = data["Table4_18"]["Freeze Dryer 18"][7]
  document.getElementById('FD18_tray7').innerHTML = data["Table4_18"]["Freeze Dryer 18"][8]
  document.getElementById('FD18_tray8').innerHTML = data["Table4_18"]["Freeze Dryer 18"][9]
  document.getElementById('FD18_tray9').innerHTML = data["Table4_18"]["Freeze Dryer 18"][10]
  document.getElementById('FD18_tray10').innerHTML = data["Table4_18"]["Freeze Dryer 18"][11]
  document.getElementById('FD18_tray11').innerHTML = data["Table4_18"]["Freeze Dryer 18"][12]
  document.getElementById('FD18_tray12').innerHTML = data["Table4_18"]["Freeze Dryer 18"][13]
  document.getElementById('FD18_tray13').innerHTML = data["Table4_18"]["Freeze Dryer 18"][14]
  document.getElementById('FD18_tray14').innerHTML = data["Table4_18"]["Freeze Dryer 18"][15]
  document.getElementById('FD18_tray15').innerHTML = data["Table4_18"]["Freeze Dryer 18"][16]

  document.getElementById('FD19').innerHTML = data["Table4_19"]["Freeze Dryer 19"][1]
  document.getElementById('FD19_tray1').innerHTML = data["Table4_19"]["Freeze Dryer 19"][2]
  document.getElementById('FD19_tray2').innerHTML = data["Table4_19"]["Freeze Dryer 19"][3]
  document.getElementById('FD19_tray3').innerHTML = data["Table4_19"]["Freeze Dryer 19"][4]
  document.getElementById('FD19_tray4').innerHTML = data["Table4_19"]["Freeze Dryer 19"][5]
  document.getElementById('FD19_tray5').innerHTML = data["Table4_19"]["Freeze Dryer 19"][6]
  document.getElementById('FD19_tray6').innerHTML = data["Table4_19"]["Freeze Dryer 19"][7]
  document.getElementById('FD19_tray7').innerHTML = data["Table4_19"]["Freeze Dryer 19"][8]
  document.getElementById('FD19_tray8').innerHTML = data["Table4_19"]["Freeze Dryer 19"][9]
  document.getElementById('FD19_tray9').innerHTML = data["Table4_19"]["Freeze Dryer 19"][10]
  document.getElementById('FD19_tray10').innerHTML = data["Table4_19"]["Freeze Dryer 19"][11]
  document.getElementById('FD19_tray11').innerHTML = data["Table4_19"]["Freeze Dryer 19"][12]
  document.getElementById('FD19_tray12').innerHTML = data["Table4_19"]["Freeze Dryer 19"][13]
  document.getElementById('FD19_tray13').innerHTML = data["Table4_19"]["Freeze Dryer 19"][14]
  document.getElementById('FD19_tray14').innerHTML = data["Table4_19"]["Freeze Dryer 19"][15]
  document.getElementById('FD19_tray15').innerHTML = data["Table4_19"]["Freeze Dryer 19"][16]

  document.getElementById('FD20').innerHTML = data["Table4_20"]["Freeze Dryer 20"][1]
  document.getElementById('FD20_tray1').innerHTML = data["Table4_20"]["Freeze Dryer 20"][2]
  document.getElementById('FD20_tray2').innerHTML = data["Table4_20"]["Freeze Dryer 20"][3]
  document.getElementById('FD20_tray3').innerHTML = data["Table4_20"]["Freeze Dryer 20"][4]
  document.getElementById('FD20_tray4').innerHTML = data["Table4_20"]["Freeze Dryer 20"][5]
  document.getElementById('FD20_tray5').innerHTML = data["Table4_20"]["Freeze Dryer 20"][6]
  document.getElementById('FD20_tray6').innerHTML = data["Table4_20"]["Freeze Dryer 20"][7]
  document.getElementById('FD20_tray7').innerHTML = data["Table4_20"]["Freeze Dryer 20"][8]
  document.getElementById('FD20_tray8').innerHTML = data["Table4_20"]["Freeze Dryer 20"][9]
  document.getElementById('FD20_tray9').innerHTML = data["Table4_20"]["Freeze Dryer 20"][10]
  document.getElementById('FD20_tray10').innerHTML = data["Table4_20"]["Freeze Dryer 20"][11]
  document.getElementById('FD20_tray11').innerHTML = data["Table4_20"]["Freeze Dryer 20"][12]
  document.getElementById('FD20_tray12').innerHTML = data["Table4_20"]["Freeze Dryer 20"][13]
  document.getElementById('FD20_tray13').innerHTML = data["Table4_20"]["Freeze Dryer 20"][14]
  document.getElementById('FD20_tray14').innerHTML = data["Table4_20"]["Freeze Dryer 20"][15]
  document.getElementById('FD20_tray15').innerHTML = data["Table4_20"]["Freeze Dryer 20"][16]

  document.getElementById('FD21').innerHTML = data["Table4_21"]["Freeze Dryer 21"][1]
  document.getElementById('FD21_tray1').innerHTML = data["Table4_21"]["Freeze Dryer 21"][2]
  document.getElementById('FD21_tray2').innerHTML = data["Table4_21"]["Freeze Dryer 21"][3]
  document.getElementById('FD21_tray3').innerHTML = data["Table4_21"]["Freeze Dryer 21"][4]
  document.getElementById('FD21_tray4').innerHTML = data["Table4_21"]["Freeze Dryer 21"][5]
  document.getElementById('FD21_tray5').innerHTML = data["Table4_21"]["Freeze Dryer 21"][6]
  document.getElementById('FD21_tray6').innerHTML = data["Table4_21"]["Freeze Dryer 21"][7]
  document.getElementById('FD21_tray7').innerHTML = data["Table4_21"]["Freeze Dryer 21"][8]
  document.getElementById('FD21_tray8').innerHTML = data["Table4_21"]["Freeze Dryer 21"][9]
  document.getElementById('FD21_tray9').innerHTML = data["Table4_21"]["Freeze Dryer 21"][10]
  document.getElementById('FD21_tray10').innerHTML = data["Table4_21"]["Freeze Dryer 21"][11]
  document.getElementById('FD21_tray11').innerHTML = data["Table4_21"]["Freeze Dryer 21"][12]
  document.getElementById('FD21_tray12').innerHTML = data["Table4_21"]["Freeze Dryer 21"][13]
  document.getElementById('FD21_tray13').innerHTML = data["Table4_21"]["Freeze Dryer 21"][14]
  document.getElementById('FD21_tray14').innerHTML = data["Table4_21"]["Freeze Dryer 21"][15]
  document.getElementById('FD21_tray15').innerHTML = data["Table4_21"]["Freeze Dryer 21"][16]

  document.getElementById('FD22').innerHTML = data["Table4_22"]["Freeze Dryer 22"][1]
  document.getElementById('FD22_tray1').innerHTML = data["Table4_22"]["Freeze Dryer 22"][2]
  document.getElementById('FD22_tray2').innerHTML = data["Table4_22"]["Freeze Dryer 22"][3]
  document.getElementById('FD22_tray3').innerHTML = data["Table4_22"]["Freeze Dryer 22"][4]
  document.getElementById('FD22_tray4').innerHTML = data["Table4_22"]["Freeze Dryer 22"][5]
  document.getElementById('FD22_tray5').innerHTML = data["Table4_22"]["Freeze Dryer 22"][6]
  document.getElementById('FD22_tray6').innerHTML = data["Table4_22"]["Freeze Dryer 22"][7]
  document.getElementById('FD22_tray7').innerHTML = data["Table4_22"]["Freeze Dryer 22"][8]
  document.getElementById('FD22_tray8').innerHTML = data["Table4_22"]["Freeze Dryer 22"][9]
  document.getElementById('FD22_tray9').innerHTML = data["Table4_22"]["Freeze Dryer 22"][10]
  document.getElementById('FD22_tray10').innerHTML = data["Table4_22"]["Freeze Dryer 22"][11]
  document.getElementById('FD22_tray11').innerHTML = data["Table4_22"]["Freeze Dryer 22"][12]
  document.getElementById('FD22_tray12').innerHTML = data["Table4_22"]["Freeze Dryer 22"][13]
  document.getElementById('FD22_tray13').innerHTML = data["Table4_22"]["Freeze Dryer 22"][14]
  document.getElementById('FD22_tray14').innerHTML = data["Table4_22"]["Freeze Dryer 22"][15]
  document.getElementById('FD22_tray15').innerHTML = data["Table4_22"]["Freeze Dryer 22"][16]





}


function changeColor(button) {
  button.classList.toggle("clicked");
    // button.disabled = true; // Disable the button after clicking if you want
}

var nameToChange;
// Function to open the dialog box
function openDialog(fd) {
  nameToChange = fd
  document.getElementById("overlay").style.display = "block";
}

// Function to submit text and display it on the page
function submitText() {
  var text = document.getElementById("textInput").value;
  document.getElementById("FD" + nameToChange).textContent = text;
  document.getElementById("overlay").style.display = "none";
  // Reset the value of the text input field
  document.getElementById("textInput").value = "";
}



function cancel() {
  document.getElementById("overlay").style.display = "none";
}
